version: 0.2

phases:
  install:
    commands:
      - echo Installing dependencies
      - npm install -g serverless
  pre_build:
    commands:
      - echo Installing source NPM dependiencies...
      - npm install
  build:
    commands:
      - echo Deployment started on `date`
      - echo Deploying with Serverless Framework
      - export SLS_DISABLE_AUTO_LOGIN=true
      - sls deploy -v -s $ENV_NAME
  post_build:
    commands:
      - echo Deployment completed on `date`
