# "service" is the name of this project. This will also be added to your AWS resource names.
service: sls-cicd

org: mabenuz

provider:
  name: aws
  runtime: nodejs20.x
  stage: dev
  region: us-east-2
  memorySize: 128
  timeout: 3

functions:
  logger:
    handler: handler.logger
    events:
      - http:
          path: message
          method: get
